// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMcpConnection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddMcpConnection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddModule(arg1) {
  return window['go']['main']['App']['AddModule'](arg1);
}

export function AddTasksAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTasksAttachment'](arg1, arg2, arg3, arg4);
}

export function AddTasksItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTasksItem'](arg1, arg2, arg3);
}

export function BrowserScreenshot(arg1) {
  return window['go']['main']['App']['BrowserScreenshot'](arg1);
}

export function BrowserStart(arg1) {
  return window['go']['main']['App']['BrowserStart'](arg1);
}

export function BrowserStatus(arg1) {
  return window['go']['main']['App']['BrowserStatus'](arg1);
}

export function BrowserStop(arg1) {
  return window['go']['main']['App']['BrowserStop'](arg1);
}

export function BrowserTabs(arg1) {
  return window['go']['main']['App']['BrowserTabs'](arg1);
}

export function CancelVoiceCapture() {
  return window['go']['main']['App']['CancelVoiceCapture']();
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function ChooseObsidianAlwaysReadFile(arg1) {
  return window['go']['main']['App']['ChooseObsidianAlwaysReadFile'](arg1);
}

export function ChooseObsidianVaultDir() {
  return window['go']['main']['App']['ChooseObsidianVaultDir']();
}

export function ChooseVaultDir() {
  return window['go']['main']['App']['ChooseVaultDir']();
}

export function CleanOldLogs(arg1) {
  return window['go']['main']['App']['CleanOldLogs'](arg1);
}

export function ClearAllLogs() {
  return window['go']['main']['App']['ClearAllLogs']();
}

export function ClearChat(arg1) {
  return window['go']['main']['App']['ClearChat'](arg1);
}

export function ClearRecentProfiles() {
  return window['go']['main']['App']['ClearRecentProfiles']();
}

export function CodesignTrustGrant() {
  return window['go']['main']['App']['CodesignTrustGrant']();
}

export function CodesignTrustStatus() {
  return window['go']['main']['App']['CodesignTrustStatus']();
}

export function CompactChat(arg1) {
  return window['go']['main']['App']['CompactChat'](arg1);
}

export function CreateChat() {
  return window['go']['main']['App']['CreateChat']();
}

export function CreateChatWithTitle(arg1) {
  return window['go']['main']['App']['CreateChatWithTitle'](arg1);
}

export function CreateCustomProvider(arg1) {
  return window['go']['main']['App']['CreateCustomProvider'](arg1);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function CreateProfileAtLocation(arg1, arg2) {
  return window['go']['main']['App']['CreateProfileAtLocation'](arg1, arg2);
}

export function CreateSelfSignedCertificate() {
  return window['go']['main']['App']['CreateSelfSignedCertificate']();
}

export function CreateSkill(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateVault(arg1) {
  return window['go']['main']['App']['CreateVault'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DeleteCustomProvider(arg1) {
  return window['go']['main']['App']['DeleteCustomProvider'](arg1);
}

export function DeleteCustomProviderConfirmed(arg1) {
  return window['go']['main']['App']['DeleteCustomProviderConfirmed'](arg1);
}

export function DeleteCustomTheme(arg1) {
  return window['go']['main']['App']['DeleteCustomTheme'](arg1);
}

export function DeleteCustomWallpaper(arg1) {
  return window['go']['main']['App']['DeleteCustomWallpaper'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function DeleteProviderCredential(arg1) {
  return window['go']['main']['App']['DeleteProviderCredential'](arg1);
}

export function DeleteProviderCredentialConfirmed(arg1) {
  return window['go']['main']['App']['DeleteProviderCredentialConfirmed'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteTasksAttachment(arg1) {
  return window['go']['main']['App']['DeleteTasksAttachment'](arg1);
}

export function DeleteTasksItem(arg1) {
  return window['go']['main']['App']['DeleteTasksItem'](arg1);
}

export function DiscardCustomProvider(arg1) {
  return window['go']['main']['App']['DiscardCustomProvider'](arg1);
}

export function GenerateRecoveryKey() {
  return window['go']['main']['App']['GenerateRecoveryKey']();
}

export function GetActiveTheme() {
  return window['go']['main']['App']['GetActiveTheme']();
}

export function GetAgentFirewall() {
  return window['go']['main']['App']['GetAgentFirewall']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAppZoomPercent() {
  return window['go']['main']['App']['GetAppZoomPercent']();
}

export function GetAutoLockMinutes() {
  return window['go']['main']['App']['GetAutoLockMinutes']();
}

export function GetBenchedProviders() {
  return window['go']['main']['App']['GetBenchedProviders']();
}

export function GetBrowserExecutable(arg1) {
  return window['go']['main']['App']['GetBrowserExecutable'](arg1);
}

export function GetChatSessionInfo(arg1) {
  return window['go']['main']['App']['GetChatSessionInfo'](arg1);
}

export function GetCustomThemes() {
  return window['go']['main']['App']['GetCustomThemes']();
}

export function GetCustomWallpaperImage(arg1) {
  return window['go']['main']['App']['GetCustomWallpaperImage'](arg1);
}

export function GetDesktopNotificationsEnabled() {
  return window['go']['main']['App']['GetDesktopNotificationsEnabled']();
}

export function GetEffectiveInstructions(arg1) {
  return window['go']['main']['App']['GetEffectiveInstructions'](arg1);
}

export function GetInstructionDocument(arg1) {
  return window['go']['main']['App']['GetInstructionDocument'](arg1);
}

export function GetInstructionSources() {
  return window['go']['main']['App']['GetInstructionSources']();
}

export function GetLastChatID() {
  return window['go']['main']['App']['GetLastChatID']();
}

export function GetLastView() {
  return window['go']['main']['App']['GetLastView']();
}

export function GetMacosPermissions() {
  return window['go']['main']['App']['GetMacosPermissions']();
}

export function GetMcpConnection(arg1) {
  return window['go']['main']['App']['GetMcpConnection'](arg1);
}

export function GetMcpServerStatus() {
  return window['go']['main']['App']['GetMcpServerStatus']();
}

export function GetMcpServerToken() {
  return window['go']['main']['App']['GetMcpServerToken']();
}

export function GetObsidianSettings() {
  return window['go']['main']['App']['GetObsidianSettings']();
}

export function GetPlanMode(arg1) {
  return window['go']['main']['App']['GetPlanMode'](arg1);
}

export function GetPromptDebugMode() {
  return window['go']['main']['App']['GetPromptDebugMode']();
}

export function GetProviderBalance(arg1) {
  return window['go']['main']['App']['GetProviderBalance'](arg1);
}

export function GetProviderCooldownMinutes() {
  return window['go']['main']['App']['GetProviderCooldownMinutes']();
}

export function GetProviderFallbackOrder() {
  return window['go']['main']['App']['GetProviderFallbackOrder']();
}

export function GetProviderStatus() {
  return window['go']['main']['App']['GetProviderStatus']();
}

export function GetRestServerStatus() {
  return window['go']['main']['App']['GetRestServerStatus']();
}

export function GetRestServerToken() {
  return window['go']['main']['App']['GetRestServerToken']();
}

export function GetSandboxSettings() {
  return window['go']['main']['App']['GetSandboxSettings']();
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function GetServerIndicator() {
  return window['go']['main']['App']['GetServerIndicator']();
}

export function GetServerTLSStatus() {
  return window['go']['main']['App']['GetServerTLSStatus']();
}

export function GetSkillDetail(arg1) {
  return window['go']['main']['App']['GetSkillDetail'](arg1);
}

export function GetSubagentMode() {
  return window['go']['main']['App']['GetSubagentMode']();
}

export function GetTasksAttachmentData(arg1) {
  return window['go']['main']['App']['GetTasksAttachmentData'](arg1);
}

export function GetUserMemoryDoc() {
  return window['go']['main']['App']['GetUserMemoryDoc']();
}

export function GetUserMemoryDocBackup() {
  return window['go']['main']['App']['GetUserMemoryDocBackup']();
}

export function GetWallpaper() {
  return window['go']['main']['App']['GetWallpaper']();
}

export function GetWallpaperGlass() {
  return window['go']['main']['App']['GetWallpaperGlass']();
}

export function GetWebServerStatus() {
  return window['go']['main']['App']['GetWebServerStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasSecret(arg1) {
  return window['go']['main']['App']['HasSecret'](arg1);
}

export function HideAllModules() {
  return window['go']['main']['App']['HideAllModules']();
}

export function HideModule(arg1) {
  return window['go']['main']['App']['HideModule'](arg1);
}

export function ImportSkillFromFile(arg1) {
  return window['go']['main']['App']['ImportSkillFromFile'](arg1);
}

export function ImportSkillsFromParent(arg1) {
  return window['go']['main']['App']['ImportSkillsFromParent'](arg1);
}

export function ImportVaultProfile(arg1) {
  return window['go']['main']['App']['ImportVaultProfile'](arg1);
}

export function InstallCustomCertificate(arg1, arg2) {
  return window['go']['main']['App']['InstallCustomCertificate'](arg1, arg2);
}

export function InvalidateWebSessions(arg1) {
  return window['go']['main']['App']['InvalidateWebSessions'](arg1);
}

export function ListChatTurns(arg1) {
  return window['go']['main']['App']['ListChatTurns'](arg1);
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function ListCustomWallpapers() {
  return window['go']['main']['App']['ListCustomWallpapers']();
}

export function ListInstructionDocuments() {
  return window['go']['main']['App']['ListInstructionDocuments']();
}

export function ListLogDates() {
  return window['go']['main']['App']['ListLogDates']();
}

export function ListLogs(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['ListLogs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function ListMcpConnections() {
  return window['go']['main']['App']['ListMcpConnections']();
}

export function ListMcpTools(arg1) {
  return window['go']['main']['App']['ListMcpTools'](arg1);
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function ListModules() {
  return window['go']['main']['App']['ListModules']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListPasswords() {
  return window['go']['main']['App']['ListPasswords']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListProviderModels(arg1) {
  return window['go']['main']['App']['ListProviderModels'](arg1);
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListTasksItems() {
  return window['go']['main']['App']['ListTasksItems']();
}

export function ListWebServerInterfaces() {
  return window['go']['main']['App']['ListWebServerInterfaces']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function MoveModule(arg1, arg2) {
  return window['go']['main']['App']['MoveModule'](arg1, arg2);
}

export function NewChatSession(arg1) {
  return window['go']['main']['App']['NewChatSession'](arg1);
}

export function NotifyDesktop(arg1, arg2) {
  return window['go']['main']['App']['NotifyDesktop'](arg1, arg2);
}

export function OnDomReady(arg1) {
  return window['go']['main']['App']['OnDomReady'](arg1);
}

export function OpenPipWindow(arg1) {
  return window['go']['main']['App']['OpenPipWindow'](arg1);
}

export function OpenSystemSettingsPane(arg1) {
  return window['go']['main']['App']['OpenSystemSettingsPane'](arg1);
}

export function PickAndUploadWallpaper() {
  return window['go']['main']['App']['PickAndUploadWallpaper']();
}

export function PickBrowserExecutable(arg1) {
  return window['go']['main']['App']['PickBrowserExecutable'](arg1);
}

export function ProbeMacosPermission(arg1) {
  return window['go']['main']['App']['ProbeMacosPermission'](arg1);
}

export function RecentMessages(arg1, arg2) {
  return window['go']['main']['App']['RecentMessages'](arg1, arg2);
}

export function RecordActivity() {
  return window['go']['main']['App']['RecordActivity']();
}

export function RecoverVault(arg1, arg2) {
  return window['go']['main']['App']['RecoverVault'](arg1, arg2);
}

export function RegenerateMcpServerToken() {
  return window['go']['main']['App']['RegenerateMcpServerToken']();
}

export function RegenerateRestServerToken() {
  return window['go']['main']['App']['RegenerateRestServerToken']();
}

export function RegenerateSelfSignedCertificate() {
  return window['go']['main']['App']['RegenerateSelfSignedCertificate']();
}

export function RegenerateWebServerSessionKey() {
  return window['go']['main']['App']['RegenerateWebServerSessionKey']();
}

export function RemoveMcpConnection(arg1) {
  return window['go']['main']['App']['RemoveMcpConnection'](arg1);
}

export function RemoveModule(arg1) {
  return window['go']['main']['App']['RemoveModule'](arg1);
}

export function RenameChat(arg1, arg2) {
  return window['go']['main']['App']['RenameChat'](arg1, arg2);
}

export function RenameCustomProvider(arg1, arg2) {
  return window['go']['main']['App']['RenameCustomProvider'](arg1, arg2);
}

export function ReportUIState(arg1) {
  return window['go']['main']['App']['ReportUIState'](arg1);
}

export function ResetInstructionDocument(arg1) {
  return window['go']['main']['App']['ResetInstructionDocument'](arg1);
}

export function ResetSkillToSeed(arg1) {
  return window['go']['main']['App']['ResetSkillToSeed'](arg1);
}

export function ResolveToolConfirmation(arg1, arg2) {
  return window['go']['main']['App']['ResolveToolConfirmation'](arg1, arg2);
}

export function ResolveUICommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveUICommand'](arg1, arg2, arg3);
}

export function SaveActiveTheme(arg1) {
  return window['go']['main']['App']['SaveActiveTheme'](arg1);
}

export function SaveCustomTheme(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomTheme'](arg1, arg2);
}

export function SaveInstructionDocument(arg1, arg2) {
  return window['go']['main']['App']['SaveInstructionDocument'](arg1, arg2);
}

export function SaveLastSession(arg1, arg2) {
  return window['go']['main']['App']['SaveLastSession'](arg1, arg2);
}

export function SavePassword(arg1) {
  return window['go']['main']['App']['SavePassword'](arg1);
}

export function SaveProviderConfig(arg1) {
  return window['go']['main']['App']['SaveProviderConfig'](arg1);
}

export function SaveSandboxSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSandboxSettings'](arg1, arg2);
}

export function SaveSkill(arg1, arg2) {
  return window['go']['main']['App']['SaveSkill'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImportFolder() {
  return window['go']['main']['App']['SelectImportFolder']();
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function SelectSkillFile() {
  return window['go']['main']['App']['SelectSkillFile']();
}

export function SendChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetAgentFirewallRules(arg1) {
  return window['go']['main']['App']['SetAgentFirewallRules'](arg1);
}

export function SetAppZoomPercent(arg1) {
  return window['go']['main']['App']['SetAppZoomPercent'](arg1);
}

export function SetAutoLockMinutes(arg1) {
  return window['go']['main']['App']['SetAutoLockMinutes'](arg1);
}

export function SetBrowserAutostart(arg1, arg2) {
  return window['go']['main']['App']['SetBrowserAutostart'](arg1, arg2);
}

export function SetBrowserExecutable(arg1, arg2) {
  return window['go']['main']['App']['SetBrowserExecutable'](arg1, arg2);
}

export function SetChatArchived(arg1, arg2) {
  return window['go']['main']['App']['SetChatArchived'](arg1, arg2);
}

export function SetChatModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetChatModel'](arg1, arg2, arg3);
}

export function SetDesktopNotificationsEnabled(arg1) {
  return window['go']['main']['App']['SetDesktopNotificationsEnabled'](arg1);
}

export function SetMcpConnectionEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetMcpConnectionEnabled'](arg1, arg2);
}

export function SetMcpServerAutostart(arg1) {
  return window['go']['main']['App']['SetMcpServerAutostart'](arg1);
}

export function SetMcpServerPort(arg1) {
  return window['go']['main']['App']['SetMcpServerPort'](arg1);
}

export function SetMcpServerTLSEnabled(arg1) {
  return window['go']['main']['App']['SetMcpServerTLSEnabled'](arg1);
}

export function SetObsidianSettings(arg1) {
  return window['go']['main']['App']['SetObsidianSettings'](arg1);
}

export function SetPlanMode(arg1, arg2) {
  return window['go']['main']['App']['SetPlanMode'](arg1, arg2);
}

export function SetPromptDebugMode(arg1) {
  return window['go']['main']['App']['SetPromptDebugMode'](arg1);
}

export function SetProviderCooldownMinutes(arg1) {
  return window['go']['main']['App']['SetProviderCooldownMinutes'](arg1);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SetProviderFallbackOrder(arg1) {
  return window['go']['main']['App']['SetProviderFallbackOrder'](arg1);
}

export function SetRestServerAutostart(arg1) {
  return window['go']['main']['App']['SetRestServerAutostart'](arg1);
}

export function SetRestServerPort(arg1) {
  return window['go']['main']['App']['SetRestServerPort'](arg1);
}

export function SetRestServerTLSEnabled(arg1) {
  return window['go']['main']['App']['SetRestServerTLSEnabled'](arg1);
}

export function SetSecret(arg1, arg2) {
  return window['go']['main']['App']['SetSecret'](arg1, arg2);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSkillEnabled'](arg1, arg2);
}

export function SetSubagentMode(arg1) {
  return window['go']['main']['App']['SetSubagentMode'](arg1);
}

export function SetUserMemoryDoc(arg1) {
  return window['go']['main']['App']['SetUserMemoryDoc'](arg1);
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}

export function SetWallpaperGlass(arg1) {
  return window['go']['main']['App']['SetWallpaperGlass'](arg1);
}

export function SetWebAssets(arg1) {
  return window['go']['main']['App']['SetWebAssets'](arg1);
}

export function SetWebServerBindMode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWebServerBindMode'](arg1, arg2, arg3);
}

export function SetWebServerEnabled(arg1) {
  return window['go']['main']['App']['SetWebServerEnabled'](arg1);
}

export function SetWebServerPort(arg1) {
  return window['go']['main']['App']['SetWebServerPort'](arg1);
}

export function SetWebServerSessionTTL(arg1) {
  return window['go']['main']['App']['SetWebServerSessionTTL'](arg1);
}

export function SetWebServerTLSEnabled(arg1) {
  return window['go']['main']['App']['SetWebServerTLSEnabled'](arg1);
}

export function ShowModule(arg1) {
  return window['go']['main']['App']['ShowModule'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartHeadless(arg1) {
  return window['go']['main']['App']['StartHeadless'](arg1);
}

export function StartMcpServer() {
  return window['go']['main']['App']['StartMcpServer']();
}

export function StartProviderBrowserAuth(arg1, arg2) {
  return window['go']['main']['App']['StartProviderBrowserAuth'](arg1, arg2);
}

export function StartProviderBrowserAuthAsync(arg1, arg2) {
  return window['go']['main']['App']['StartProviderBrowserAuthAsync'](arg1, arg2);
}

export function StartRestServer() {
  return window['go']['main']['App']['StartRestServer']();
}

export function StartVoiceCapture() {
  return window['go']['main']['App']['StartVoiceCapture']();
}

export function StartWebServer() {
  return window['go']['main']['App']['StartWebServer']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopChat(arg1) {
  return window['go']['main']['App']['StopChat'](arg1);
}

export function StopMcpServer() {
  return window['go']['main']['App']['StopMcpServer']();
}

export function StopRestServer() {
  return window['go']['main']['App']['StopRestServer']();
}

export function StopVoiceCapture() {
  return window['go']['main']['App']['StopVoiceCapture']();
}

export function StopWebServer() {
  return window['go']['main']['App']['StopWebServer']();
}

export function StreamChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['StreamChatMessage'](arg1, arg2, arg3);
}

export function SuggestThemeFromPalette(arg1) {
  return window['go']['main']['App']['SuggestThemeFromPalette'](arg1);
}

export function SwitchProvider(arg1, arg2) {
  return window['go']['main']['App']['SwitchProvider'](arg1, arg2);
}

export function TestMcpConnection(arg1) {
  return window['go']['main']['App']['TestMcpConnection'](arg1);
}

export function TestObsidianAccess() {
  return window['go']['main']['App']['TestObsidianAccess']();
}

export function TestProviderConnection(arg1) {
  return window['go']['main']['App']['TestProviderConnection'](arg1);
}

export function TestSandboxCommand(arg1) {
  return window['go']['main']['App']['TestSandboxCommand'](arg1);
}

export function TranscribeAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranscribeAudio'](arg1, arg2, arg3);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateMcpConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateMcpConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateNoteFlags(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNoteFlags'](arg1, arg2, arg3);
}

export function UpdateNoteInPrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteInPrompt'](arg1, arg2);
}

export function UpdateTasksItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTasksItem'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadWallpaperFromPath(arg1) {
  return window['go']['main']['App']['UploadWallpaperFromPath'](arg1);
}

export function VaultStatus() {
  return window['go']['main']['App']['VaultStatus']();
}

export function VaultTouchIDAvailable() {
  return window['go']['main']['App']['VaultTouchIDAvailable']();
}

export function VaultTouchIDEnroll(arg1) {
  return window['go']['main']['App']['VaultTouchIDEnroll'](arg1);
}

export function VaultTouchIDHasPassword() {
  return window['go']['main']['App']['VaultTouchIDHasPassword']();
}

export function VaultTouchIDRemove() {
  return window['go']['main']['App']['VaultTouchIDRemove']();
}

export function VaultTouchIDRepair() {
  return window['go']['main']['App']['VaultTouchIDRepair']();
}

export function VaultTouchIDUnlock() {
  return window['go']['main']['App']['VaultTouchIDUnlock']();
}

export function VerifyRecoveryKey(arg1) {
  return window['go']['main']['App']['VerifyRecoveryKey'](arg1);
}
