// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {domain} from '../models';
import {context} from '../models';
import {fs} from '../models';

export function AddMcpConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<dto.McpConnectionResult>;

export function AddModule(arg1:string):Promise<dto.ModulesResult>;

export function AddTasksAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<dto.TasksAttachmentResult>;

export function AddTasksItem(arg1:string,arg2:string,arg3:string):Promise<dto.TasksItemResult>;

export function BrowserScreenshot(arg1:string):Promise<dto.BrowserScreenshotResult>;

export function BrowserStart(arg1:string):Promise<dto.BrowserStatusResult>;

export function BrowserStatus(arg1:string):Promise<dto.BrowserStatusResult>;

export function BrowserStop(arg1:string):Promise<dto.BrowserStatusResult>;

export function BrowserTabs(arg1:string):Promise<dto.BrowserTabsResult>;

export function CancelVoiceCapture():Promise<dto.VoiceCaptureResult>;

export function ChangePassword(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function ChooseObsidianAlwaysReadFile(arg1:string):Promise<dto.ObsidianFileDialogResult>;

export function ChooseObsidianVaultDir():Promise<dto.FolderDialogResult>;

export function ChooseVaultDir():Promise<dto.VaultStatusResponse>;

export function CleanOldLogs(arg1:number):Promise<dto.LogRetentionResult>;

export function ClearAllLogs():Promise<dto.LogRetentionResult>;

export function ClearChat(arg1:string):Promise<dto.ChatOperationResult>;

export function ClearRecentProfiles():Promise<dto.OperationResult>;

export function CodesignTrustGrant():Promise<dto.OperationResult>;

export function CodesignTrustStatus():Promise<dto.CodesignTrustResult>;

export function CompactChat(arg1:string):Promise<dto.ChatOperationResult>;

export function CreateChat():Promise<domain.Chat>;

export function CreateChatWithTitle(arg1:string):Promise<domain.Chat>;

export function CreateCustomProvider(arg1:string):Promise<domain.ProviderOperationResult>;

export function CreateNote(arg1:string,arg2:string,arg3:boolean):Promise<dto.NoteResult>;

export function CreateProfileAtLocation(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function CreateSelfSignedCertificate():Promise<dto.ServerTLSStatus>;

export function CreateSkill(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:Array<domain.SkillFile>):Promise<dto.SkillResult>;

export function CreateVault(arg1:string):Promise<dto.OperationResult>;

export function DeleteChat(arg1:string):Promise<dto.ChatOperationResult>;

export function DeleteCustomProvider(arg1:string):Promise<domain.ProviderOperationResult>;

export function DeleteCustomProviderConfirmed(arg1:string):Promise<domain.ProviderOperationResult>;

export function DeleteCustomTheme(arg1:string):Promise<dto.OperationResult>;

export function DeleteCustomWallpaper(arg1:string):Promise<dto.WallpaperUploadResult>;

export function DeleteNote(arg1:string):Promise<dto.NoteResult>;

export function DeletePassword(arg1:string):Promise<dto.OperationResult>;

export function DeleteProviderCredential(arg1:string):Promise<domain.ProviderOperationResult>;

export function DeleteProviderCredentialConfirmed(arg1:string):Promise<domain.ProviderOperationResult>;

export function DeleteSecret(arg1:string):Promise<dto.OperationResult>;

export function DeleteSkill(arg1:string):Promise<dto.SkillResult>;

export function DeleteTasksAttachment(arg1:string):Promise<dto.TasksAttachmentResult>;

export function DeleteTasksItem(arg1:string):Promise<dto.TasksItemResult>;

export function DiscardCustomProvider(arg1:string):Promise<domain.ProviderOperationResult>;

export function GenerateRecoveryKey():Promise<dto.OperationResult>;

export function GetActiveTheme():Promise<string>;

export function GetAgentFirewall():Promise<dto.AgentFirewallState>;

export function GetAppVersion():Promise<string>;

export function GetAppZoomPercent():Promise<number>;

export function GetAutoLockMinutes():Promise<number>;

export function GetBenchedProviders():Promise<Array<string>>;

export function GetBrowserExecutable(arg1:string):Promise<dto.BrowserExecutableResult>;

export function GetChatSessionInfo(arg1:string):Promise<dto.ChatSessionInfo>;

export function GetCustomThemes():Promise<Record<string, any>>;

export function GetCustomWallpaperImage(arg1:string):Promise<dto.WallpaperImageResult>;

export function GetDesktopNotificationsEnabled():Promise<boolean>;

export function GetEffectiveInstructions(arg1:boolean):Promise<dto.EffectiveInstructionsResult>;

export function GetInstructionDocument(arg1:string):Promise<dto.InstructionReadResult>;

export function GetInstructionSources():Promise<dto.InstructionSourcesResult>;

export function GetLastChatID():Promise<string>;

export function GetLastView():Promise<string>;

export function GetMacosPermissions():Promise<dto.MacosPermissionsResult>;

export function GetMcpConnection(arg1:string):Promise<dto.McpConnectionResult>;

export function GetMcpServerStatus():Promise<dto.APIServerStatus>;

export function GetMcpServerToken():Promise<dto.SecretResult>;

export function GetObsidianSettings():Promise<dto.ObsidianSettings>;

export function GetPlanMode(arg1:string):Promise<dto.PlanModeResult>;

export function GetPromptDebugMode():Promise<dto.PromptDebugModeResponse>;

export function GetProviderBalance(arg1:string):Promise<domain.ProviderBalanceResult>;

export function GetProviderCooldownMinutes():Promise<number>;

export function GetProviderFallbackOrder():Promise<Array<string>>;

export function GetProviderStatus():Promise<domain.ProviderStatus>;

export function GetRestServerStatus():Promise<dto.APIServerStatus>;

export function GetRestServerToken():Promise<dto.SecretResult>;

export function GetSandboxSettings():Promise<dto.SandboxSettingsResult>;

export function GetSecret(arg1:string):Promise<dto.SecretResult>;

export function GetServerIndicator():Promise<dto.ServerIndicator>;

export function GetServerTLSStatus():Promise<dto.ServerTLSStatus>;

export function GetSkillDetail(arg1:string):Promise<dto.SkillDetailResult>;

export function GetSubagentMode():Promise<dto.SubagentModeResponse>;

export function GetTasksAttachmentData(arg1:string):Promise<dto.TasksAttachmentDataResult>;

export function GetUserMemoryDoc():Promise<dto.UserMemoryDocResult>;

export function GetUserMemoryDocBackup():Promise<dto.UserMemoryDocResult>;

export function GetWallpaper():Promise<string>;

export function GetWallpaperGlass():Promise<number>;

export function GetWebServerStatus():Promise<dto.WebServerStatus>;

export function Greet(arg1:string):Promise<string>;

export function HasSecret(arg1:string):Promise<dto.SecretResult>;

export function HideAllModules():Promise<dto.ModulesResult>;

export function HideModule(arg1:string):Promise<dto.ModulesResult>;

export function ImportSkillFromFile(arg1:string):Promise<dto.SkillResult>;

export function ImportSkillsFromParent(arg1:string):Promise<dto.ImportSkillsResult>;

export function ImportVaultProfile(arg1:string):Promise<dto.OperationResult>;

export function InstallCustomCertificate(arg1:string,arg2:string):Promise<dto.ServerTLSStatus>;

export function InvalidateWebSessions(arg1:string):Promise<void>;

export function ListChatTurns(arg1:string):Promise<Array<domain.LLMTurn>>;

export function ListChats():Promise<Array<domain.Chat>>;

export function ListCustomWallpapers():Promise<dto.WallpaperUploadResult>;

export function ListInstructionDocuments():Promise<dto.InstructionsListResult>;

export function ListLogDates():Promise<dto.LogDatesResult>;

export function ListLogs(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number,arg12:number):Promise<dto.LogsResult>;

export function ListMcpConnections():Promise<dto.McpConnectionsResult>;

export function ListMcpTools(arg1:string):Promise<dto.McpToolsResult>;

export function ListMessages(arg1:string):Promise<Array<domain.Message>>;

export function ListModules():Promise<dto.ModulesResult>;

export function ListNotes():Promise<dto.NotesResult>;

export function ListPasswords():Promise<dto.PasswordsResult>;

export function ListProfiles():Promise<Array<domain.ProfileInfo>>;

export function ListProviderModels(arg1:string):Promise<domain.ProviderModelsResult>;

export function ListSecrets():Promise<Array<string>>;

export function ListSkills():Promise<dto.SkillsResult>;

export function ListTasksItems():Promise<dto.TasksResult>;

export function ListWebServerInterfaces():Promise<dto.WebBindInterfacesResult>;

export function LockVault():Promise<dto.OperationResult>;

export function MoveModule(arg1:string,arg2:boolean):Promise<dto.ModulesResult>;

export function NewChatSession(arg1:string):Promise<dto.ChatOperationResult>;

export function NotifyDesktop(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OpenPipWindow(arg1:string):Promise<dto.OperationResult>;

export function OpenSystemSettingsPane(arg1:string):Promise<dto.OperationResult>;

export function PickAndUploadWallpaper():Promise<dto.WallpaperUploadResult>;

export function PickBrowserExecutable(arg1:string):Promise<dto.BrowserExecutableResult>;

export function ProbeMacosPermission(arg1:string):Promise<dto.MacosProbeResult>;

export function RecentMessages(arg1:string,arg2:number):Promise<Array<domain.Message>>;

export function RecordActivity():Promise<void>;

export function RecoverVault(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function RegenerateMcpServerToken():Promise<dto.SecretResult>;

export function RegenerateRestServerToken():Promise<dto.SecretResult>;

export function RegenerateSelfSignedCertificate():Promise<dto.ServerTLSStatus>;

export function RegenerateWebServerSessionKey():Promise<dto.WebServerStatus>;

export function RemoveMcpConnection(arg1:string):Promise<dto.McpConnectionResult>;

export function RemoveModule(arg1:string):Promise<dto.ModulesResult>;

export function RenameChat(arg1:string,arg2:string):Promise<dto.ChatOperationResult>;

export function RenameCustomProvider(arg1:string,arg2:string):Promise<domain.ProviderOperationResult>;

export function ReportUIState(arg1:Record<string, any>):Promise<void>;

export function ResetInstructionDocument(arg1:string):Promise<dto.InstructionSaveResult>;

export function ResetSkillToSeed(arg1:string):Promise<dto.SkillResult>;

export function ResolveToolConfirmation(arg1:string,arg2:boolean):Promise<dto.OperationResult>;

export function ResolveUICommand(arg1:string,arg2:string,arg3:string):Promise<dto.OperationResult>;

export function SaveActiveTheme(arg1:string):Promise<dto.OperationResult>;

export function SaveCustomTheme(arg1:string,arg2:Record<string, any>):Promise<dto.OperationResult>;

export function SaveInstructionDocument(arg1:string,arg2:string):Promise<dto.InstructionSaveResult>;

export function SaveLastSession(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function SavePassword(arg1:domain.PasswordEntry):Promise<dto.PasswordResult>;

export function SaveProviderConfig(arg1:domain.ProviderSaveConfigInput):Promise<domain.ProviderOperationResult>;

export function SaveSandboxSettings(arg1:string,arg2:Array<string>):Promise<dto.SandboxSettingsResult>;

export function SaveSkill(arg1:string,arg2:Array<domain.SkillFile>):Promise<dto.SkillResult>;

export function SelectFolder():Promise<dto.FolderDialogResult>;

export function SelectImportFolder():Promise<dto.FolderDialogResult>;

export function SelectProfile(arg1:string):Promise<dto.OperationResult>;

export function SelectSkillFile():Promise<dto.FolderDialogResult>;

export function SendChatMessage(arg1:string,arg2:string,arg3:Array<domain.Attachment>):Promise<dto.ChatSendResult>;

export function SendMessage(arg1:string,arg2:string):Promise<domain.AgentReply>;

export function SetAgentFirewallRules(arg1:Array<domain.FirewallRule>):Promise<dto.AgentFirewallState>;

export function SetAppZoomPercent(arg1:number):Promise<dto.OperationResult>;

export function SetAutoLockMinutes(arg1:number):Promise<dto.OperationResult>;

export function SetBrowserAutostart(arg1:string,arg2:boolean):Promise<dto.BrowserStatusResult>;

export function SetBrowserExecutable(arg1:string,arg2:string):Promise<dto.BrowserExecutableResult>;

export function SetChatArchived(arg1:string,arg2:boolean):Promise<dto.ChatOperationResult>;

export function SetChatModel(arg1:string,arg2:string,arg3:string):Promise<dto.ChatModelResult>;

export function SetDesktopNotificationsEnabled(arg1:boolean):Promise<dto.OperationResult>;

export function SetMcpConnectionEnabled(arg1:string,arg2:boolean):Promise<dto.McpConnectionResult>;

export function SetMcpServerAutostart(arg1:boolean):Promise<dto.APIServerStatus>;

export function SetMcpServerPort(arg1:number):Promise<dto.APIServerStatus>;

export function SetMcpServerTLSEnabled(arg1:boolean):Promise<dto.APIServerStatus>;

export function SetObsidianSettings(arg1:dto.ObsidianSettings):Promise<dto.OperationResult>;

export function SetPlanMode(arg1:string,arg2:boolean):Promise<dto.PlanModeResult>;

export function SetPromptDebugMode(arg1:boolean):Promise<dto.OperationResult>;

export function SetProviderCooldownMinutes(arg1:number):Promise<dto.OperationResult>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<domain.ProviderOperationResult>;

export function SetProviderFallbackOrder(arg1:Array<string>):Promise<dto.OperationResult>;

export function SetRestServerAutostart(arg1:boolean):Promise<dto.APIServerStatus>;

export function SetRestServerPort(arg1:number):Promise<dto.APIServerStatus>;

export function SetRestServerTLSEnabled(arg1:boolean):Promise<dto.APIServerStatus>;

export function SetSecret(arg1:string,arg2:string):Promise<dto.OperationResult>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<dto.SkillResult>;

export function SetSubagentMode(arg1:string):Promise<dto.OperationResult>;

export function SetUserMemoryDoc(arg1:string):Promise<dto.UserMemoryDocResult>;

export function SetWallpaper(arg1:string):Promise<dto.OperationResult>;

export function SetWallpaperGlass(arg1:number):Promise<dto.OperationResult>;

export function SetWebAssets(arg1:fs.FS):Promise<void>;

export function SetWebServerBindMode(arg1:string,arg2:string,arg3:Array<string>):Promise<dto.WebServerStatus>;

export function SetWebServerEnabled(arg1:boolean):Promise<dto.WebServerStatus>;

export function SetWebServerPort(arg1:number):Promise<dto.WebServerStatus>;

export function SetWebServerSessionTTL(arg1:number):Promise<dto.WebServerStatus>;

export function SetWebServerTLSEnabled(arg1:boolean):Promise<dto.WebServerStatus>;

export function ShowModule(arg1:string):Promise<dto.ModulesResult>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartHeadless(arg1:context.Context):Promise<void>;

export function StartMcpServer():Promise<dto.APIServerStatus>;

export function StartProviderBrowserAuth(arg1:string,arg2:string):Promise<domain.ProviderOperationResult>;

export function StartProviderBrowserAuthAsync(arg1:string,arg2:string):Promise<Record<string, any>>;

export function StartRestServer():Promise<dto.APIServerStatus>;

export function StartVoiceCapture():Promise<dto.VoiceCaptureResult>;

export function StartWebServer():Promise<dto.WebServerStatus>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopChat(arg1:string):Promise<dto.ChatOperationResult>;

export function StopMcpServer():Promise<dto.APIServerStatus>;

export function StopRestServer():Promise<dto.APIServerStatus>;

export function StopVoiceCapture():Promise<dto.AudioTranscriptionResult>;

export function StopWebServer():Promise<dto.WebServerStatus>;

export function StreamChatMessage(arg1:string,arg2:string,arg3:Array<domain.Attachment>):Promise<dto.ChatSendResult>;

export function SuggestThemeFromPalette(arg1:Array<string>):Promise<dto.ThemeSuggestionResult>;

export function SwitchProvider(arg1:string,arg2:string):Promise<domain.ProviderOperationResult>;

export function TestMcpConnection(arg1:string):Promise<dto.McpConnectionTestResult>;

export function TestObsidianAccess():Promise<dto.ObsidianTestResult>;

export function TestProviderConnection(arg1:string):Promise<domain.ProviderTestResult>;

export function TestSandboxCommand(arg1:string):Promise<dto.SandboxTestResult>;

export function TranscribeAudio(arg1:string,arg2:string,arg3:string):Promise<dto.AudioTranscriptionResult>;

export function UnlockVault(arg1:string):Promise<dto.OperationResult>;

export function UpdateMcpConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string,arg7:boolean):Promise<dto.McpConnectionResult>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<dto.NoteResult>;

export function UpdateNoteFlags(arg1:string,arg2:boolean,arg3:boolean):Promise<dto.NoteResult>;

export function UpdateNoteInPrompt(arg1:string,arg2:boolean):Promise<dto.NoteResult>;

export function UpdateTasksItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<dto.TasksItemResult>;

export function UploadWallpaperFromPath(arg1:string):Promise<dto.WallpaperUploadResult>;

export function VaultStatus():Promise<dto.VaultStatusResponse>;

export function VaultTouchIDAvailable():Promise<boolean>;

export function VaultTouchIDEnroll(arg1:string):Promise<dto.OperationResult>;

export function VaultTouchIDHasPassword():Promise<boolean>;

export function VaultTouchIDRemove():Promise<dto.OperationResult>;

export function VaultTouchIDRepair():Promise<dto.OperationResult>;

export function VaultTouchIDUnlock():Promise<dto.OperationResult>;

export function VerifyRecoveryKey(arg1:string):Promise<dto.OperationResult>;
